python -u main.py \
    --is_training 0 \
    --root_path ./dataset/competition/train-5min/ \
    --flow_data_path flow.csv \
    --speed_data_path speed.csv \
    --d_model 64 \
    --d_ff 32 \
    --gpu 0 \
    --num_kernels 6 \
    --top_k 5 \
    --lradj type3 \
    --patience 20 \
    --freq h \
    --learning_rate 0.001\
    --batch_size 32\
    --e_layers 2\
    --dropout 0.2\