python -u main.py \
    --is_training 0 \
    --root_path ./dataset/competition/train-5min/ \
    --data_path flow.csv \
    --d_model 256 \
    --d_ff 256 \
    --gpu 1 \
    --num_kernels 6 \
    --top_k 5 \
    --lradj type3 \
    --patience 10 \
    --freq t \
    --learning_rate 0.001\
    --batch_size 16\